image: archlinux/base

stages:
    - format
    - build

format:
    stage: format 
    before_script:
        - pacman -Sy --noconfirm 
        - pacman -S python pycodestyle --noconfirm 
    script:
        - pycodestyle investment-charges-comparison.py

build:
    stage: build
    before_script:
        - pacman -Sy --noconfirm 
        - pacman -S python python-matplotlib --noconfirm 
    script:
        - python -m py_compile investment-charges-comparison.py 

