image: archlinux/base


stages:
    - formatting
    - builds


formatting:
    stage: formatting
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S python python-pycodestyle --noconfirm
    script:
        - pycodestyle investment-charges-comparison.py --max-line-length=140


builds:
    stage: builds
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S python python-pip --noconfirm
        - pip install -r requirements.txt
    script:
        - python -m py_compile investment-charges-comparison.py
