stages:
  - clean-git-history-checking
  - conventional-commits-linting
  - formatting
  - compiling


services:
  - docker:dind


variables:
  DOCKER_HOST: tcp://docker:2375


image:
  name: earthly/earthly
  entrypoint: ["/bin/sh", "-c"]


clean-git-history-checking:
  stage: clean-git-history-checking
  script:
    # Check all the commits in the branch.
    - earthly --ci +clean-git-history-checking --from "origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}"
  rules:
    - if: $CI_MERGE_REQUEST_ID


conventional-commits-linting:
  stage: conventional-commits-linting
  script:
    # Lint all the commits in the branch.
    - earthly --ci +conventional-commits-linting --from "origin/${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}"
  rules:
    - if: $CI_MERGE_REQUEST_ID


formatting:
  stage: formatting
  script:
    - earthly --ci +check-formatting
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


compiling:
  stage: compiling
  script:
    - earthly --ci +compiling
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
