image: archlinux/base

stages:
    - build

build:
    stage: build
    before_script:
        - pacman -Sy --noconfirm 
        - pacman -S python --noconfirm 
    script:
        - python -m py_compile Investment-Charges-Comparison.py 

