image: archlinux/base

stages:
    - build

build:
    stage: build
    before_script:
        - pacman -Sy --noconfirm 
        - pacman -S python python-matplotlib --noconfirm 
    script:
        - python -m py_compile investment-charges-comparison.py 

